services:
  api:
    build:
      context: .
    environment:
      - DATABASE_URL=mysql://root:root@db:3306/contact_manager
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION_TIME=${JWT_EXPIRATION_TIME}
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npx prisma migrate deploy && npm run dev"
    ports:
      - "3000:3000"

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: contact_manager
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysql -uroot -proot -e 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  db-data:
